"""empty message

Revision ID: 4989ad30b02d
Revises: c99a12b31f43
Create Date: 2017-03-12 01:29:32.952692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4989ad30b02d'
down_revision = 'c99a12b31f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('biography', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('datejoined', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('user_profile', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'password')
    op.drop_column('user_profile', 'lastname')
    op.drop_column('user_profile', 'image')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'firstname')
    op.drop_column('user_profile', 'datejoined')
    op.drop_column('user_profile', 'biography')
    op.drop_column('user_profile', 'age')
    # ### end Alembic commands ###
